# Generated by Django 2.1.7 on 2019-04-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pu_date',
            new_name='pub_date',
        ),
    ]
